### ISSUE TITLE
インストールしようとすると「Incompatible Workflow」と言われます

### ISSUE THREAD

**Issue by shimbaco** [nukosuke/alfred-annict-workflow#9]
最高のプラグインをありがとうございます!! インストールしようとしたのですが、下記のように「Incompatible Workflow」という画面が出てしまいました。これは何か設定等が足りないからでしょうか?

![image](https://cloud.githubusercontent.com/assets/56767/18921277/22bd0668-85df-11e6-9f92-5b922de71863.png)
### 環境
- Mac OS X 10.11.6
- Alfred 2.8.6
- `~/.annict/config.json` 設定済み

```
$ cat ~/.annict/config.json
{
  "access_token": "xxxxxxx"
}
```

**Comment by nukosuke** [comment]
こちらこそ最高のサービスをありがとうございます！

一応Alfred 2の出力形式にも対応して書いたのですが、 ワークフローをExportしたAlfredのバージョンが3だったのでおそらくそれが原因です。申し訳ありません 🙇 

お持ちのPowerpackライセンスはv3へアップグレード可能なMega Supporter Licenseでしょうか？

**Comment by nukosuke** [comment]
v2でExportし直したものを用意したので試してみてください 🙏 

https://github.com/nukosuke/alfred-annict-workflow/releases/download/v0.0.0-alpha/Annict2.alfredworkflow

**Comment by shimbaco** [comment]
おおお、ありがとうございます! 無事インストールできました! すごく便利ですね!
こちらは閉じさせて頂きます!
